[project]
name = "web-vibe"
version = "0.1.0"
description = "Hackathon project to provide feedback to content writers and web-designers."
readme = "README.md"
requires-python = ">=3.10"
dependencies = []
